type ControlElement = HTMLInputElement & HTMLSelectElement & HTMLTextAreaElement;

function q<T extends Element = HTMLElement>(selector: string): T {
  const element = document.querySelector(selector);
  if (!element) {
    throw new Error(`Missing required DOM element: ${selector}`);
  }
  return element as T;
}

function qa<T extends Element = HTMLElement>(selector: string): T[] {
  return Array.from(document.querySelectorAll(selector)) as T[];
}

export function queryZenithDom() {
  const hud = q<HTMLCanvasElement>("#hud");
  return {
    canvas: q<HTMLCanvasElement>("#viewer"),
    hud,
    hudContext: hud.getContext("2d"),
    demoCursor: q<HTMLElement>("#demoCursor"),
    gpuState: q<HTMLElement>("#gpuState"),
    workflowSteps: qa<HTMLElement>("[data-flow-step]"),
    flowSourceState: q<HTMLElement>("#flowSourceState"),
    flowPlateState: q<HTMLElement>("#flowPlateState"),
    flowInpaintState: q<HTMLElement>("#flowInpaintState"),
    flowMotionState: q<HTMLElement>("#flowMotionState"),
    flowExportState: q<HTMLElement>("#flowExportState"),
    mediaInput: q<HTMLInputElement>("#mediaInput"),
    platesInput: q<HTMLInputElement>("#platesInput"),
    commitPlateMap: q<HTMLButtonElement>("#commitPlateMap"),
    exportPlateMap: q<HTMLButtonElement>("#exportPlateMap"),
    platesReadout: q<HTMLElement>("#platesReadout"),
    patchEditor: q<HTMLElement>("#patchEditor"),
    patchTransform: q<HTMLElement>("#patchTransform"),
    autoArrangePatches: q<HTMLButtonElement>("#autoArrangePatches"),
    resetPatch: q<HTMLButtonElement>("#resetPatch"),
    resetPatchWarp: q<HTMLButtonElement>("#resetPatchWarp"),
    flipPatchX: q<HTMLButtonElement>("#flipPatchX"),
    flipPatchY: q<HTMLButtonElement>("#flipPatchY"),
    runwayInpaint: q<HTMLButtonElement>("#runwayInpaint"),
    useRunwayOutput: q<HTMLButtonElement>("#useRunwayOutput"),
    exportRunwayOutput: q<HTMLButtonElement>("#exportRunwayOutput"),
    runwayResults: q<HTMLElement>("#runwayResults"),
    inpaintReadout: q<HTMLElement>("#inpaintReadout"),
    runwayDepthMap: q<HTMLButtonElement>("#runwayDepthMap"),
    previewDepthMotion: q<HTMLButtonElement>("#previewDepthMotion"),
    exportDepthMotion: q<HTMLButtonElement>("#exportDepthMotion"),
    codexSeedancePrompt: q<HTMLButtonElement>("#codexSeedancePrompt"),
    runwaySeedance: q<HTMLButtonElement>("#runwaySeedance"),
    showSeedanceOutput: q<HTMLButtonElement>("#showSeedanceOutput"),
    exportSeedanceOutput: q<HTMLButtonElement>("#exportSeedanceOutput"),
    copyDepthMotionConfig: q<HTMLButtonElement>("#copyDepthMotionConfig"),
    exportDepthMotionConfig: q<HTMLButtonElement>("#exportDepthMotionConfig"),
    codexImageSeedancePrompt: q<HTMLButtonElement>("#codexImageSeedancePrompt"),
    runwayImageSeedance: q<HTMLButtonElement>("#runwayImageSeedance"),
    seedanceResults: q<HTMLElement>("#seedanceResults"),
    seedancePromptPreview: q<HTMLElement>("#seedancePromptPreview"),
    seedancePromptState: q<HTMLElement>("#seedancePromptState"),
    seedanceStillReference: q<HTMLElement>("#seedanceStillReference"),
    seedanceMotionReference: q<HTMLElement>("#seedanceMotionReference"),
    imageSeedancePromptPreview: q<HTMLElement>("#imageSeedancePromptPreview"),
    imageSeedancePromptState: q<HTMLElement>("#imageSeedancePromptState"),
    imageSeedanceReference: q<HTMLElement>("#imageSeedanceReference"),
    depthMotionReadout: q<HTMLElement>("#depthMotionReadout"),
    saveWorkspace: q<HTMLButtonElement>("#saveWorkspace"),
    exportWorkspaceState: q<HTMLButtonElement>("#exportWorkspaceState"),
    restoreWorkspace: q<HTMLButtonElement>("#restoreWorkspace"),
    clearWorkspace: q<HTMLButtonElement>("#clearWorkspace"),
    sessionReadout: q<HTMLElement>("#sessionReadout"),
    saveVersion: q<HTMLButtonElement>("#saveVersion"),
    applyVersion: q<HTMLButtonElement>("#applyVersion"),
    deleteVersion: q<HTMLButtonElement>("#deleteVersion"),
    exportVersion: q<HTMLButtonElement>("#exportVersion"),
    importVersion: q<HTMLInputElement>("#importVersion"),
    versionSelect: q<HTMLSelectElement>("#versionSelect"),
    versionGallery: q<HTMLElement>("#versionGallery"),
    versionReadout: q<HTMLElement>("#versionReadout"),
    playToggle: q<HTMLButtonElement>("#playToggle"),
    stepBack: q<HTMLButtonElement>("#stepBack"),
    stepForward: q<HTMLButtonElement>("#stepForward"),
    timeline: q<HTMLInputElement>("#timeline"),
    playbackRate: q<HTMLSelectElement>("#playbackRate"),
    timeReadout: q<HTMLOutputElement>("#timeReadout"),
    video: q<HTMLVideoElement>("#videoSource"),
    dropOverlay: q<HTMLElement>("#dropOverlay"),
    sidePanel: q<HTMLElement>("#sidePanel"),
    workspaceTabs: qa<HTMLButtonElement>("[data-workspace-tab]"),
    workspaceSections: qa<HTMLElement>("[data-workspace]"),
    viewButtons: qa<HTMLButtonElement>("[data-view]"),
    lookZenith: q<HTMLButtonElement>("#lookZenith"),
    lookNorth: q<HTMLButtonElement>("#lookNorth"),
    lookHorizon: q<HTMLButtonElement>("#lookHorizon"),
    captureFrameButton: q<HTMLButtonElement>("#captureFrame"),
    captureSquareFrame: q<HTMLButtonElement>("#captureSquareFrame"),
    recordCanvas: q<HTMLButtonElement>("#recordCanvas"),
    demoPlateCompose: q<HTMLButtonElement>("#demoPlateCompose"),
    demoViewTour: q<HTMLButtonElement>("#demoViewTour"),
    demoInpaintPulse: q<HTMLButtonElement>("#demoInpaintPulse"),
    captureReadout: q<HTMLElement>("#captureReadout"),
    exportPresetButton: q<HTMLButtonElement>("#exportPreset"),
    sourceReadout: q<HTMLElement>("#sourceReadout"),
    mediaReadout: q<HTMLElement>("#mediaReadout"),
    viewReadout: q<HTMLElement>("#viewReadout"),
    uploadReadout: q<HTMLElement>("#uploadReadout"),
    perfReadout: q<HTMLElement>("#perfReadout"),
    controls: {
      fov: q<ControlElement>("#fov"),
      renderScale: q<ControlElement>("#renderScale"),
      meshQuality: q<ControlElement>("#meshQuality"),
      radiusScale: q<ControlElement>("#radiusScale"),
      rotation: q<ControlElement>("#rotation"),
      domeTilt: q<ControlElement>("#domeTilt"),
      theaterEyeDrop: q<ControlElement>("#theaterEyeDrop"),
      theaterSeatBack: q<ControlElement>("#theaterSeatBack"),
      theaterPitch: q<ControlElement>("#theaterPitch"),
      customCurve: q<ControlElement>("#customCurve"),
      shellShade: q<ControlElement>("#shellShade"),
      floorOpacity: q<ControlElement>("#floorOpacity"),
      exposure: q<ControlElement>("#exposure"),
      overlayOpacity: q<ControlElement>("#overlayOpacity"),
      projectionMode: q<ControlElement>("#projectionMode"),
      mirror: q<ControlElement>("#mirror"),
      autoRotate: q<ControlElement>("#autoRotate"),
      showRings: q<ControlElement>("#showRings"),
      showSpokes: q<ControlElement>("#showSpokes"),
      showHorizon: q<ControlElement>("#showHorizon"),
      showLabels: q<ControlElement>("#showLabels"),
      showSourceCircle: q<ControlElement>("#showSourceCircle"),
      showZenith: q<ControlElement>("#showZenith"),
      plateCount: q<ControlElement>("#plateCount"),
      plateFit: q<ControlElement>("#plateFit"),
      plateFeather: q<ControlElement>("#plateFeather"),
      editPlacement: q<ControlElement>("#editPlacement"),
      activePlate: q<ControlElement>("#activePlate"),
      plateCornerMode: q<ControlElement>("#plateCornerMode"),
      patchAzimuth: q<ControlElement>("#patchAzimuth"),
      patchRadius: q<ControlElement>("#patchRadius"),
      patchSpin: q<ControlElement>("#patchSpin"),
      patchOpacity: q<ControlElement>("#patchOpacity"),
      runwayQuality: q<ControlElement>("#runwayQuality"),
      runwayOutputCount: q<ControlElement>("#runwayOutputCount"),
      runwayPrompt: q<ControlElement>("#runwayPrompt"),
      depthPrompt: q<ControlElement>("#depthPrompt"),
      seedancePrompt: q<ControlElement>("#seedancePrompt"),
      seedancePromptMode: q<ControlElement>("#seedancePromptMode"),
      imageSeedancePrompt: q<ControlElement>("#imageSeedancePrompt"),
      imageSeedancePromptMode: q<ControlElement>("#imageSeedancePromptMode"),
      imageSeedanceRatio: q<ControlElement>("#imageSeedanceRatio"),
      depthPolarity: q<ControlElement>("#depthPolarity"),
      depthGuideMode: q<ControlElement>("#depthGuideMode"),
      depthSketchSize: q<ControlElement>("#depthSketchSize"),
      depthNear: q<ControlElement>("#depthNear"),
      depthFar: q<ControlElement>("#depthFar"),
      depthSketchDuration: q<ControlElement>("#depthSketchDuration"),
      depthSketchFps: q<ControlElement>("#depthSketchFps"),
      depthMotionGain: q<ControlElement>("#depthMotionGain"),
      depthContrast: q<ControlElement>("#depthContrast"),
      depthGuideNoise: q<ControlElement>("#depthGuideNoise"),
      depthSketchYaw: q<ControlElement>("#depthSketchYaw"),
      depthSketchPitch: q<ControlElement>("#depthSketchPitch"),
      depthSketchRoll: q<ControlElement>("#depthSketchRoll"),
      depthSketchTruck: q<ControlElement>("#depthSketchTruck"),
      depthSketchLift: q<ControlElement>("#depthSketchLift"),
      depthSketchPush: q<ControlElement>("#depthSketchPush"),
      depthSketchGapFill: q<ControlElement>("#depthSketchGapFill"),
    },
  };
}

export type ZenithDom = ReturnType<typeof queryZenithDom>;
export type ZenithControls = ZenithDom["controls"];
