type ControlElement = HTMLInputElement & HTMLSelectElement & HTMLTextAreaElement;

function q<T extends Element = HTMLElement>(selector: string): T {
  const element = document.querySelector(selector);
  if (!element) {
    throw new Error(`Missing required DOM element: ${selector}`);
  }
  return element as T;
}

function qa<T extends Element = HTMLElement>(selector: string): T[] {
  return Array.from(document.querySelectorAll(selector)) as T[];
}

export function queryZenithDom() {
  const hud = q<HTMLCanvasElement>("#hud");
  return {
    canvas: q<HTMLCanvasElement>("#viewer"),
    hud,
    hudContext: hud.getContext("2d"),
    commitPlateMap: q<HTMLButtonElement>("#commitPlateMap"),
    exportPlateMap: q<HTMLButtonElement>("#exportPlateMap"),
    platesReadout: q<HTMLElement>("#platesReadout"),
    patchEditor: q<HTMLElement>("#patchEditor"),
    patchTransform: q<HTMLElement>("#patchTransform"),
    autoArrangePatches: q<HTMLButtonElement>("#autoArrangePatches"),
    resetPatch: q<HTMLButtonElement>("#resetPatch"),
    resetPatchWarp: q<HTMLButtonElement>("#resetPatchWarp"),
    flipPatchX: q<HTMLButtonElement>("#flipPatchX"),
    flipPatchY: q<HTMLButtonElement>("#flipPatchY"),
    runwayInpaint: q<HTMLButtonElement>("#runwayInpaint"),
    useRunwayOutput: q<HTMLButtonElement>("#useRunwayOutput"),
    exportRunwayOutput: q<HTMLButtonElement>("#exportRunwayOutput"),
    runwayResults: q<HTMLElement>("#runwayResults"),
    inpaintReadout: q<HTMLElement>("#inpaintReadout"),
    runwayDepthMap: q<HTMLButtonElement>("#runwayDepthMap"),
    previewDepthMotion: q<HTMLButtonElement>("#previewDepthMotion"),
    exportDepthMotion: q<HTMLButtonElement>("#exportDepthMotion"),
    runwaySeedance: q<HTMLButtonElement>("#runwaySeedance"),
    showSeedanceOutput: q<HTMLButtonElement>("#showSeedanceOutput"),
    exportSeedanceOutput: q<HTMLButtonElement>("#exportSeedanceOutput"),
    copyDepthMotionConfig: q<HTMLButtonElement>("#copyDepthMotionConfig"),
    exportDepthMotionConfig: q<HTMLButtonElement>("#exportDepthMotionConfig"),
    exportDepthMap: q<HTMLButtonElement>("#exportDepthMap"),
    exportGeneratedPrompts: q<HTMLButtonElement>("#exportGeneratedPrompts"),
    captureDepthFinalState: q<HTMLButtonElement>("#captureDepthFinalState"),
    reconstructDepthFinalState: q<HTMLButtonElement>("#reconstructDepthFinalState"),
    exportDepthFinalState: q<HTMLButtonElement>("#exportDepthFinalState"),
    exportDepthFinalHandoff: q<HTMLButtonElement>("#exportDepthFinalHandoff"),
    runwayStateSeedance: q<HTMLButtonElement>("#runwayStateSeedance"),
    runwayImageSeedance: q<HTMLButtonElement>("#runwayImageSeedance"),
    seedanceResults: q<HTMLElement>("#seedanceResults"),
    fulldomeProfileReadout: q<HTMLElement>("#fulldomeProfileReadout"),
    fulldomeQcReadout: q<HTMLElement>("#fulldomeQcReadout"),
    depthMotionPresetDescription: q<HTMLElement>("#depthMotionPresetDescription"),
    stateEndpointResults: q<HTMLElement>("#stateEndpointResults"),
    exportCaveFaces: q<HTMLButtonElement>("#exportCaveFaces"),
    caveExportReadout: q<HTMLElement>("#caveExportReadout"),
    playToggle: q<HTMLButtonElement>("#playToggle"),
    stepBack: q<HTMLButtonElement>("#stepBack"),
    stepForward: q<HTMLButtonElement>("#stepForward"),
    timeline: q<HTMLInputElement>("#timeline"),
    playbackRate: q<HTMLSelectElement>("#playbackRate"),
    timeReadout: q<HTMLOutputElement>("#timeReadout"),
    video: q<HTMLVideoElement>("#videoSource"),
    sidePanel: q<HTMLElement>("#sidePanel"),
    viewButtons: qa<HTMLButtonElement>("[data-view]"),
    lookZenith: q<HTMLButtonElement>("#lookZenith"),
    lookNadir: q<HTMLButtonElement>("#lookNadir"),
    lookNorth: q<HTMLButtonElement>("#lookNorth"),
    lookHorizon: q<HTMLButtonElement>("#lookHorizon"),
    captureFrameButton: q<HTMLButtonElement>("#captureFrame"),
    captureSquareFrame: q<HTMLButtonElement>("#captureSquareFrame"),
    recordCanvas: q<HTMLButtonElement>("#recordCanvas"),
    captureReadout: q<HTMLElement>("#captureReadout"),
    exportPresetButton: q<HTMLButtonElement>("#exportPreset"),
    controls: {
      fov: q<ControlElement>("#fov"),
      renderScale: q<ControlElement>("#renderScale"),
      meshQuality: q<ControlElement>("#meshQuality"),
      radiusScale: q<ControlElement>("#radiusScale"),
      rotation: q<ControlElement>("#rotation"),
      domeTilt: q<ControlElement>("#domeTilt"),
      theaterEyeDrop: q<ControlElement>("#theaterEyeDrop"),
      theaterSeatBack: q<ControlElement>("#theaterSeatBack"),
      theaterPitch: q<ControlElement>("#theaterPitch"),
      shellShade: q<ControlElement>("#shellShade"),
      floorOpacity: q<ControlElement>("#floorOpacity"),
      exposure: q<ControlElement>("#exposure"),
      overlayOpacity: q<ControlElement>("#overlayOpacity"),
      sourceProjection: q<ControlElement>("#sourceProjection"),
      mirror: q<ControlElement>("#mirror"),
      autoRotate: q<ControlElement>("#autoRotate"),
      showRings: q<ControlElement>("#showRings"),
      showSpokes: q<ControlElement>("#showSpokes"),
      showHorizon: q<ControlElement>("#showHorizon"),
      showLabels: q<ControlElement>("#showLabels"),
      showSourceCircle: q<ControlElement>("#showSourceCircle"),
      showZenith: q<ControlElement>("#showZenith"),
      showCaveMask: (document.querySelector("#showCaveMask") as ControlElement | null) || undefined,
      invertCaveMask: (document.querySelector("#invertCaveMask") as ControlElement | null) || undefined,
      plateCount: q<ControlElement>("#plateCount"),
      plateFit: q<ControlElement>("#plateFit"),
      plateFeather: q<ControlElement>("#plateFeather"),
      editPlacement: q<ControlElement>("#editPlacement"),
      activePlate: q<ControlElement>("#activePlate"),
      plateCornerMode: q<ControlElement>("#plateCornerMode"),
      patchAzimuth: q<ControlElement>("#patchAzimuth"),
      patchRadius: q<ControlElement>("#patchRadius"),
      patchSpin: q<ControlElement>("#patchSpin"),
      patchOpacity: q<ControlElement>("#patchOpacity"),
      runwayQuality: q<ControlElement>("#runwayQuality"),
      runwayOutputCount: q<ControlElement>("#runwayOutputCount"),
      runwayPrompt: q<ControlElement>("#runwayPrompt"),
      depthPrompt: q<ControlElement>("#depthPrompt"),
      seedancePrompt: q<ControlElement>("#seedancePrompt"),
      seedancePromptMode: q<ControlElement>("#seedancePromptMode"),
      depthMotionPreset: q<ControlElement>("#depthMotionPreset"),
      stateSeedancePrompt: q<ControlElement>("#stateSeedancePrompt"),
      stateSeedancePromptMode: q<ControlElement>("#stateSeedancePromptMode"),
      stateSeedanceRatio: q<ControlElement>("#stateSeedanceRatio"),
      imageSeedancePrompt: q<ControlElement>("#imageSeedancePrompt"),
      imageSeedancePromptMode: q<ControlElement>("#imageSeedancePromptMode"),
      imageSeedanceRatio: q<ControlElement>("#imageSeedanceRatio"),
      caveSource: q<ControlElement>("#caveSource"),
      caveProjection: q<ControlElement>("#caveProjection"),
      caveFaceSize: q<ControlElement>("#caveFaceSize"),
      depthPolarity: q<ControlElement>("#depthPolarity"),
      depthGuideMode: q<ControlElement>("#depthGuideMode"),
      depthSketchSize: q<ControlElement>("#depthSketchSize"),
      depthNear: q<ControlElement>("#depthNear"),
      depthFar: q<ControlElement>("#depthFar"),
      depthSketchDuration: q<ControlElement>("#depthSketchDuration"),
      depthSketchFps: q<ControlElement>("#depthSketchFps"),
      depthMotionGain: q<ControlElement>("#depthMotionGain"),
      depthContrast: q<ControlElement>("#depthContrast"),
      depthGuideNoise: q<ControlElement>("#depthGuideNoise"),
      depthSketchYaw: q<ControlElement>("#depthSketchYaw"),
      depthSketchPitch: q<ControlElement>("#depthSketchPitch"),
      depthSketchRoll: q<ControlElement>("#depthSketchRoll"),
      depthSketchTruck: q<ControlElement>("#depthSketchTruck"),
      depthSketchLift: q<ControlElement>("#depthSketchLift"),
      depthSketchPush: q<ControlElement>("#depthSketchPush"),
      depthSketchGapFill: q<ControlElement>("#depthSketchGapFill"),
    },
  };
}

export type ZenithDom = ReturnType<typeof queryZenithDom>;
export type ZenithControls = ZenithDom["controls"];
