import { artifactIsReady, getArtifact } from "../artifacts/artifact-store.svelte.js";
import type {
  ArtifactSlotId,
  OperatorAvailability,
  OperatorDefinition,
  OperatorId,
  WorkflowStageId,
} from "../artifacts/artifact-types.js";

export const OPERATORS: OperatorDefinition[] = [
  {
    id: "import-plate-sketch",
    stage: "start",
    attachTo: "plate-sketch",
    label: "Import Plate Sketch",
    description: "Replace the current composition handoff with a committed fulldome Plate Sketch PNG.",
    inputs: [],
    output: "plate-sketch",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "choose-projection",
    stage: "start",
    attachTo: "plate-sketch",
    label: "Choose Projection Profile",
    description: "Apply the selected fulldome projection profile to every artifact in this chain.",
    inputs: ["plate-sketch"],
    output: "plate-sketch",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "import-source",
    stage: "start",
    attachTo: "start-state",
    label: "Import Start State",
    description: "Import a clean square domemaster image as the Start State.",
    inputs: [],
    output: "start-state",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "commit-plates",
    stage: "start",
    attachTo: "plate-sketch",
    label: "Commit Plate Sketch",
    description: "Promote the current fulldome composition handoff as the Plate Sketch for inpaint.",
    inputs: ["plate-sketch"],
    output: "plate-sketch",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "repair-start-state",
    stage: "start",
    attachTo: "plate-sketch",
    label: "Repair / Inpaint Start",
    description: "Use a paid image model to inpaint the Plate Sketch into a clean Start State.",
    inputs: ["plate-sketch"],
    output: "start-state",
    kind: "paid-api",
    requiresConfirmation: true,
    confirmationTitle: "Run paid Start State repair?",
    confirmationBody:
      "This will send the visible Plate Sketch and editable repair prompt to the configured image generation endpoint.",
    promptFields: [{ id: "repair", label: "Plate Sketch -> Start State prompt", artifactId: "start-state", rows: 7 }],
  },
  {
    id: "generate-start-depth",
    stage: "start",
    attachTo: "start-depth",
    label: "Generate Start Depth",
    description: "Generate a depth map for the Start State.",
    inputs: ["start-state"],
    output: "start-depth",
    kind: "paid-api",
    requiresConfirmation: true,
    confirmationTitle: "Run paid Start Depth generation?",
    confirmationBody: "This will send Image 1 / Start State to the configured depth-image endpoint.",
    promptFields: [{ id: "startDepth", label: "Start depth prompt", artifactId: "start-depth", rows: 6 }],
  },
  {
    id: "import-start-depth",
    stage: "start",
    attachTo: "start-depth",
    label: "Import Start Depth",
    description: "Use an existing grayscale depth map for the Start State.",
    inputs: ["start-state"],
    output: "start-depth",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "export-start-depth",
    stage: "start",
    attachTo: "start-depth",
    label: "Export Start Depth",
    description: "Download the selected Start Depth PNG/image.",
    inputs: ["start-depth"],
    output: "start-depth",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "preview-motion-draft",
    stage: "motion",
    attachTo: "motion-draft",
    label: "Preview 2.5D Motion Draft",
    description: "Use local 2.5D motion settings to create or refresh the guide/proxy motion artifact.",
    inputs: ["start-state", "start-depth"],
    output: "motion-draft",
    kind: "local",
    requiresConfirmation: false,
    configFields: [
      "duration",
      "fps",
      "size",
      "radiusScale",
      "yaw",
      "pitch",
      "roll",
      "truck",
      "lift",
      "push",
      "depthGain",
      "nearMeters",
      "farMeters",
      "depthContrast",
      "gapFillPasses",
      "polarity",
      "guideMode",
      "emptyBackground",
    ],
  },
  {
    id: "export-motion-proxy",
    stage: "motion",
    attachTo: "motion-draft",
    label: "Export Motion Proxy",
    description: "Download the local Motion Draft video/handoff material.",
    inputs: ["motion-draft"],
    output: "motion-draft",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "export-motion-config",
    stage: "motion",
    attachTo: "motion-draft",
    label: "Export Motion Config",
    description: "Download the exact local 2.5D depth-motion settings as JSON.",
    inputs: ["start-state", "start-depth"],
    output: "motion-draft",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "capture-displaced-endpoint",
    stage: "motion",
    attachTo: "displaced-endpoint",
    label: "Capture Displaced Endpoint",
    description: "Capture the final rough frame from the Motion Draft for reconstruction.",
    inputs: ["start-state", "start-depth", "motion-draft"],
    output: "displaced-endpoint",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "reconstruct-end-state",
    stage: "end",
    attachTo: "end-state",
    label: "Reconstruct End State",
    description:
      "Use the displaced endpoint as structure and the Start State as style/material reference to produce a clean End State.",
    inputs: ["start-state", "displaced-endpoint"],
    output: "end-state",
    kind: "paid-api",
    requiresConfirmation: true,
    confirmationTitle: "Run paid End State reconstruction?",
    confirmationBody:
      "This will send the displaced endpoint as structural source and the Start State as style/material reference.",
    promptFields: [{ id: "reconstruct", label: "Endpoint reconstruction prompt", artifactId: "end-state", rows: 8 }],
  },
  {
    id: "generate-end-depth",
    stage: "end",
    attachTo: "end-depth",
    label: "Generate End Depth",
    description: "Generate a second depth map for the reconstructed End State.",
    inputs: ["end-state"],
    output: "end-depth",
    kind: "paid-api",
    requiresConfirmation: true,
    confirmationTitle: "Run paid End Depth generation?",
    confirmationBody: "This will send the reconstructed End State to the configured depth-image endpoint.",
    promptFields: [{ id: "endDepth", label: "End depth prompt", artifactId: "end-depth", rows: 6 }],
  },
  {
    id: "import-end-depth",
    stage: "end",
    attachTo: "end-depth",
    label: "Import End Depth",
    description: "Use an existing grayscale depth map for the reconstructed End State.",
    inputs: ["end-state"],
    output: "end-depth",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "export-end-depth",
    stage: "end",
    attachTo: "end-depth",
    label: "Export End Depth",
    description: "Download the selected End Depth PNG/image.",
    inputs: ["end-depth"],
    output: "end-depth",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "generate-video-take",
    stage: "video",
    attachTo: "video-take",
    label: "Generate Video Take",
    description:
      "Generate from Image 1 = Start State, Image 2 = End State, and Video 1 = Motion Draft guide/proxy.",
    inputs: ["start-state", "end-state", "motion-draft"],
    output: "video-take",
    kind: "paid-api",
    requiresConfirmation: true,
    confirmationTitle: "Run paid Seedance video take?",
    confirmationBody:
      "This will send the Start State, End State, Motion Draft video, and visible prompt to the configured video endpoint.",
    promptFields: [{ id: "video", label: "Video take prompt", artifactId: "video-take", rows: 9 }],
  },
  {
    id: "inspect-qc",
    stage: "deliver",
    attachTo: "deliverables",
    label: "Inspect QC",
    description: "Review the concrete fulldome production checklist.",
    inputs: ["video-take"],
    output: "deliverables",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "export-deliverables",
    stage: "deliver",
    attachTo: "deliverables",
    label: "Export Delivery Manifest",
    description: "Download a manifest with selected artifact roles, prompts, projection, and QC state.",
    inputs: ["video-take"],
    output: "deliverables",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "save-project",
    stage: "deliver",
    attachTo: "deliverables",
    label: "Save Project JSON",
    description: "Download a portable artifact project snapshot with prompts, config, QC, and embedded media.",
    inputs: [],
    output: "deliverables",
    kind: "local",
    requiresConfirmation: false,
  },
  {
    id: "load-project",
    stage: "deliver",
    attachTo: "deliverables",
    label: "Load Project JSON",
    description: "Restore a saved artifact project snapshot from disk.",
    inputs: [],
    output: "deliverables",
    kind: "local",
    requiresConfirmation: false,
  },
];

export function getOperator(operatorId: OperatorId): OperatorDefinition {
  const operator = OPERATORS.find((item) => item.id === operatorId);
  if (!operator) throw new Error(`Unknown operator: ${operatorId}`);
  return operator;
}

export function operatorsForArtifact(artifactId: ArtifactSlotId): OperatorAvailability[] {
  return OPERATORS.filter((operator) => operator.attachTo === artifactId).map((operator) => ({
    operator,
    disabledReason: disabledReasonForOperator(operator),
  }));
}

export function operatorsForStage(stageId: WorkflowStageId): OperatorAvailability[] {
  return OPERATORS.filter((operator) => operator.stage === stageId).map((operator) => ({
    operator,
    disabledReason: disabledReasonForOperator(operator),
  }));
}

export function disabledReasonForOperator(operator: OperatorDefinition): string | null {
  const missing = operator.inputs.filter((id) => !artifactIsReady(id));
  if (missing.length > 0) {
    return `Needs ${missing.map((id) => getArtifact(id).label).join(", ")}.`;
  }
  return null;
}
